server:
  port: 8083
spring:
  application:
    name: employee
  datasource:
    url: jdbc:mysql://localhost/bhhc
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

